<?php

/**
 * Implements hook_menu();
 */
function vbmenu_menu() {
  $items = array();
  $items['vbmenu'] = array(
    'title' => 'Voorbeeld menu',
    'access arguments' => array('access content'),
    'page callback' => 'vb_menu_menu1',
  );
  $items['vbmenu/%'] =array(
    'title' => 'Voorbeeld van wildcard',
    'access arguments' => array('access content'),
    'page arguments' => array(1), //0=vbmenu, 1=%
    'page callback' => 'vb_menu_menu2',
    'file' => 'vbmenu.callback.inc' //file met callback
  );
  return $items;
}

/**
 * page callback voor vbmenu
 * 
 * @return array render array
 */
function vb_menu_menu1() {
  $output = array();
  $output['#markup'] = t('Dit is het eerste voorbeeld');
  return $output;
}

