<?php

/**
 * Implements hook_menu();
 */
function vbmenu_menu() {
  $items = array();
  $items['vbmenu'] = array(
    'title' => 'Voorbeeld menu',
    'access arguments' => array('access content'),
    'page callback' => 'vb_menu_menu1',
  );
  return $items;
}

/**
 * page callback voor vbmenu
 * 
 * @return render array() 
 */
function vb_menu_menu1() {
  $output = array();
  $output['#markup'] = t('Dit is het eerste voorbeeld');
  return $output;
}
